// api para consultar peliculas
export const URL_SERVER = 'https://api.themoviedb.org/3/movie/';
// api de imagenes
export const API_TOKEN = 'fe7efc74d84900307b2fc58249a15d62';
export const MOVIE_ORIGINAL = 'https://image.tmdb.org/t/p/original';
export const MOVIE_W500 = 'https://image.tmdb.org/t/p/w500';
// eventos del sistema
export const HANDLER_LIST_MOVIES_TOP_RATED_SUCCESS =
  'HANDLER_LIST_MOVIES_TOP_RATED_SUCCESS';
export const HANDLER_LIST_MOVIES_TOP_RATED_FAILURE =
  'HANDLER_LIST_MOVIES_TOP_RATED_FAILURE';
export const HANDLER_LIST_MOVIES_TOP_RATED_REQUEST =
  'HANDLER_LIST_MOVIES_TOP_RATED_REQUEST';
export const HANDLER_CLEAR_LIST_MOVIES = 'HANDLER_CLEAR_LIST_MOVIES';
export const HANDLER_CLEAR_MOVIE = 'HANDLER_CLEAR_MOVIE';
export const LOADING = 'loading';
export const NOT_LOADING = 'not_loading';
export const HANDLER_SEARCH_MOVIE_SUCCESS = 'HANDLER_SEARCH_MOVIE_SUCCESS';
export const HANDLER_SEARCH_MOVIE_FAILURE = 'HANDLER_SEARCH_MOVIE_FAILURE';
export const HANDLER_SEARCH_MOVIE_REQUEST = 'HANDLER_SEARCH_MOVIE_REQUEST';
export const HANDLER_SEARCH_DETAILS_MOVIE_SUCCESS =
  'HANDLER_SEARCH_DETAILS_MOVIE_SUCCESS';
export const HANDLER_SEARCH_DETAILS_MOVIE_FAILURE =
  'HANDLER_SEARCH_DETAILS_MOVIE_FAILURE';
export const HANDLER_SEARCH_DETAILS_MOVIE_REQUEST =
  'HANDLER_SEARCH_DETAILS_MOVIE_REQUEST';
export const HANDLER_LIST_MOVIES_POPULAR_REQUEST =
  'HANDLER_LIST_MOVIES_POPULAR_REQUEST';
export const HANDLER_LIST_MOVIES_POPULAR_SUCCESS =
  'HANDLER_LIST_MOVIES_POPULAR_SUCCESS';
export const HANDLER_LIST_MOVIES_POPULAR_FAILURE =
  'HANDLER_LIST_MOVIES_POPULAR_FAILURE';
export const HANDLER_LIST_TOP_OF_MOVIES_REQUEST =
  'HANDLER_LIST_TOP_OF_MOVIES_REQUEST';
export const HANDLER_LIST_TOP_OF_MOVIES_SUCCESS =
  'HANDLER_LIST_TOP_OF_MOVIES_SUCCESS';
export const HANDLER_LIST_TOP_OF_MOVIES_FAILURE =
  'HANDLER_LIST_TOP_OF_MOVIES_FAILURE';
